# 8.5.x -> matches our docs
# jdk11-temurin -> matches our CI
# focal -> matches killbill/base
FROM tomcat:8.5.90-jdk11-temurin-focal

COPY killbill-admin-ui-standalone.war /usr/local/tomcat/webapps/ROOT.war
